steps:
  docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: '${CI_REPO_OWNER}/${CI_REPO_NAME}'
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms: linux/amd64,linux/arm64

when:
  - event: push
    branch: master
